---
title: "STATS 700-002 Class 2.\\newline The coalescent"
author:
  - "Edward Ionides and Aaron King"
date: September 4, 2025
date-format: long
format:
  beamer:
    cite-method: natbib
    biblio-style: apalike
    header-includes: |
      \setbeamertemplate{footline}[page number]

bibliography: ../phylodynamics.bib
---

## The coalescent

Kingman, J. F. C. (1982). The coalescent. _Stochastic Processes and their Applications_, 13(3), 235-248. [https://doi.org/10.1016/0304-4149(82)90011-4](https://doi.org/10.1016/0304-4149(82)90011-4).


## Section 1

- How does the construction of section 1 relate to a genealogical tree?

- What does the assumption (1.3) mean?

- Is the relation $\prec$ defined in (1.4) an order relation?

- Verify that $q_\xi=\binom{|\xi|}{2}$, as claimed in (1.6).

- In terms of genealogical trees, what is the interpretation of the $D_t$ process introduced in (1.8)?

- In terms of genealogical trees, what does the *transit time* $T$ introduced in (1.11) correspond to?

## Theorem 1

- What do we have to know about continuous time Markov chains to follow this proof?

- Why does equation (2.1) hold?

- Verify equation (2.2).


## Theorems 3 and 4

- Summarize, in words, what is accomplished by these results.

## Relevance to phylodynamics

- It may be hard at this point to see the relevance of Kingman's coalescent to practical phylodynamic inference.

- Given what we know at this point, conjecture how Kingman's coalescent might be used, or extended to be useful.





